# Generated by Django 4.0.4 on 2022-05-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
