# Generated by Django 4.0.4 on 2022-05-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workout',
        ),
    ]
